services:
  # main containers
  app:
    image: node:20.11.1
    volumes:
      - $PWD/app:/home/node/app
    working_dir: /home/node/app
    command: bash -c "npm install && npm start"
    environment:
      - APP_PORT=${APP_PORT}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.3.0
    volumes:
      - $PWD/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - LANG=C.UTF-8

  caddy:
    image: caddy:2.7.6
    ports:
      - 8080:80
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - mysql
      - app

  # support containers
  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - mysql
